version = 1
SPDX-PackageName = "opendatahub-timeseries-api"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-timeseries-api"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".pre-commit-config.yaml", ".editorconfig", ".env.example", ".mailmap", "calls.http", "LICENSE", "src/**/**.properties", "src/**/**.json", "src/**/**.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
